### ISSUE TITLE
Feature: Support sending Logs

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-telemetry-sdk-go#23]
Add support for sending logs as specified in the [Telemetry SDK Spec](https://github.com/newrelic/newrelic-telemetry-sdk-specs/blob/master/capabilities.md#logs)

**Comment by Miriam-R** [comment]
We want to update the spec that's referenced here and our intention is to support whatever the Go OTel SiG consensus is regarding logging.
