### ISSUE TITLE
Shared timeout may be causing data to be dropped

### ISSUE THREAD

**Issue by ardias** [newrelic/newrelic-telemetry-sdk-go#30]
Hi,
in this line [here](https://github.com/newrelic/newrelic-telemetry-sdk-go/blob/e3d912863ace96681b2b66ebffdb0acc5f874ff2/telemetry/harvester.go#L347) we see that there could be more than one request that needs to be done. 
The context timeout is shared with all the requests, so is it possible that if one or more requests take longer to respond that the context times out and the next requests (and data) are dropped?

**Comment by RichVanderwal** [comment]
Hi @ardias, thanks for waiting so long for a reply!

You're right, if the entire harvest takes more than the HarvestTimeout period, all the remaining data for that harvest will be dropped. If you're regularly seeing messages in your logs about `harvest cancelled or timed out`, consider changing the defaultHarvestTimeout to be something greater.

I'm closing this issue, but let me know if you have any comments or concerns about this approach.
